// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("tetragon")
	ScopeName = "github.com/cilium/otelcol-tetragon/receiver/tetragonreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
