extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  file_storage/checkpoint:
    directory: /var/lib/otelcol/checkpoint

receivers:
  tetragon:
    endpoint: ${env:TETRAGON_ENDPOINT}
    tls:
      insecure: true
    keepalive:
      time: 30s
      permit_without_stream: true


processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 5s
    limit_mib: 256
    spike_limit_mib: 64

  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: [os]

exporters:
  otlp_http/openobserve:
    endpoint: ${env:OTEL_EXPORTER_ENDPOINT}
    headers:
      Authorization: Basic ${env:OTEL_AUTH}
      stream-name: ${env:OTEL_STREAM_NAME}
    sending_queue:
      enabled: true
      storage: file_storage/checkpoint

service:
  extensions: [health_check, file_storage/checkpoint]
  telemetry:
    logs:
      level: ${env:OTEL_LOG_LEVEL:-info}
    metrics:
      readers:
        - periodic:
            interval: 30000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: ${env:OTEL_EXPORTER_ENDPOINT}/v1/metrics
                headers:
                  Authorization: Basic ${env:OTEL_AUTH}
  pipelines:
    logs/tetragon:
      receivers: [tetragon]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp_http/openobserve]
